name: lafferty_sriver_2023
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- affine=2.3.1
- aiohttp=3.8.3
- aiosignal=1.3.1
- alsa-lib=1.2.8
- anyio=3.6.2
- appdirs=1.4.4
- argon2-cffi=21.3.0
- argon2-cffi-bindings=21.2.0
- asciitree=0.3.3
- asttokens=2.2.1
- async-timeout=4.0.2
- attr=2.5.1
- attrs=22.2.0
- babel=2.11.0
- backcall=0.2.0
- backports=1.0
- backports.functools_lru_cache=1.6.4
- beautifulsoup4=4.11.1
- bleach=5.0.1
- blosc=1.21.3
- bokeh=2.4.3
- boltons=21.0.0
- boost-cpp=1.78.0
- bottleneck=1.3.5
- branca=0.6.0
- brotli=1.0.9
- brotli-bin=1.0.9
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2022.12.7
- cairo=1.16.0
- cartopy=0.21.1
- certifi=2022.12.7
- cf_xarray=0.7.6
- cffi=1.15.1
- cfitsio=4.2.0
- cftime=1.6.2
- charset-normalizer=2.1.1
- click=8.1.3
- click-plugins=1.1.1
- cligj=0.7.2
- cloudpickle=2.2.0
- comm=0.1.2
- contourpy=1.0.7
- cryptography=39.0.0
- curl=7.87.0
- cycler=0.11.0
- cytoolz=0.12.0
- dask=2022.12.1
- dask-core=2022.12.1
- dask-jobqueue=0.8.1
- dask-labextension=6.0.0
- dbus=1.13.6
- debugpy=1.6.5
- decorator=5.1.1
- defusedxml=0.7.1
- distributed=2022.12.1
- entrypoints=0.4
- esmf=8.2.0
- esmpy=8.2.0
- executing=1.2.0
- expat=2.5.0
- fasteners=0.17.3
- fftw=3.3.10
- fiona=1.8.22
- flit-core=3.8.0
- folium=0.14.0
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.1
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.38.0
- freetype=2.12.1
- freexl=1.0.6
- frozenlist=1.3.3
- fsspec=2022.11.0
- gdal=3.6.2
- geopandas=0.12.2
- geopandas-base=0.12.2
- geos=3.11.1
- geotiff=1.7.1
- gettext=0.21.1
- giflib=5.2.1
- glib=2.74.1
- glib-tools=2.74.1
- gst-plugins-base=1.21.3
- gstreamer=1.21.3
- gstreamer-orc=0.4.33
- hdf4=4.2.15
- hdf5=1.12.2
- heapdict=1.0.1
- icu=70.1
- idna=3.4
- importlib-metadata=6.0.0
- importlib_metadata=6.0.0
- importlib_resources=5.10.2
- ipykernel=6.20.1
- ipython=8.8.0
- ipython_genutils=0.2.0
- jack=1.9.21
- jedi=0.18.2
- jinja2=3.1.2
- joblib=1.2.0
- jpeg=9e
- json-c=0.16
- json5=0.9.5
- jsonpickle=3.0.0
- jsonschema=4.17.3
- jupyter-server-proxy=3.2.2
- jupyter_client=7.4.9
- jupyter_core=5.1.3
- jupyter_events=0.6.3
- jupyter_server=2.1.0
- jupyter_server_terminals=0.4.4
- jupyterlab=3.5.2
- jupyterlab_pygments=0.2.2
- jupyterlab_server=2.18.0
- kealib=1.5.0
- keyutils=1.6.1
- kiwisolver=1.4.4
- krb5=1.20.1
- lame=3.100
- lcms2=2.14
- ld_impl_linux-64=2.39
- lerc=4.0.0
- libaec=1.0.6
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcap=2.66
- libcblas=3.9.0
- libclang=15.0.7
- libclang13=15.0.7
- libcups=2.3.3
- libcurl=7.87.0
- libdb=6.2.32
- libdeflate=1.14
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.10
- libffi=3.4.2
- libflac=1.4.2
- libgcc-ng=12.2.0
- libgcrypt=1.10.1
- libgdal=3.6.2
- libgfortran-ng=12.2.0
- libgfortran5=12.2.0
- libglib=2.74.1
- libgomp=12.2.0
- libgpg-error=1.46
- libiconv=1.17
- libjpeg-turbo=2.1.4
- libkml=1.3.0
- liblapack=3.9.0
- libllvm11=11.1.0
- libllvm15=15.0.7
- libnetcdf=4.8.1
- libnghttp2=1.51.0
- libnsl=2.0.0
- libogg=1.3.4
- libopenblas=0.3.21
- libopus=1.3.1
- libpng=1.6.39
- libpq=15.1
- librttopo=1.1.0
- libsndfile=1.2.0
- libsodium=1.0.18
- libspatialindex=1.9.3
- libspatialite=5.0.1
- libsqlite=3.40.0
- libssh2=1.10.0
- libstdcxx-ng=12.2.0
- libsystemd0=252
- libtiff=4.5.0
- libtool=2.4.7
- libudev1=252
- libuuid=2.32.1
- libuv=1.44.2
- libvorbis=1.3.7
- libwebp-base=1.2.4
- libxcb=1.13
- libxkbcommon=1.0.3
- libxml2=2.10.3
- libzip=1.9.2
- libzlib=1.2.13
- llvmlite=0.39.1
- locket=1.0.0
- lz4=4.2.0
- lz4-c=1.9.3
- mapclassify=2.4.3
- markupsafe=2.1.1
- matplotlib=3.6.2
- matplotlib-base=3.6.2
- matplotlib-inline=0.1.6
- mistune=2.0.4
- mpg123=1.31.1
- mpi=1.0
- mpi4py=3.1.4
- mpich=4.0.3
- mscorefonts=0.0.1
- msgpack-python=1.0.4
- multidict=6.0.4
- munch=2.5.0
- munkres=1.1.4
- mysql-common=8.0.31
- mysql-libs=8.0.31
- nbclassic=0.4.8
- nbclient=0.7.2
- nbconvert=7.2.7
- nbconvert-core=7.2.7
- nbconvert-pandoc=7.2.7
- nbformat=5.7.3
- nc-time-axis=1.4.1
- ncurses=6.3
- nest-asyncio=1.5.6
- netcdf-fortran=4.6.0
- netcdf4=1.6.2
- networkx=3.0
- nodejs=18.12.1
- notebook=6.5.2
- notebook-shim=0.2.2
- nspr=4.35
- nss=3.82
- numba=0.56.4
- numcodecs=0.11.0
- numpy=1.23.5
- openjpeg=2.5.0
- openssl=3.0.7
- packaging=23.0
- pandas=1.5.2
- pandoc=2.19.2
- pandocfilters=1.5.0
- parso=0.8.3
- partd=1.3.0
- patsy=0.5.3
- pcre2=10.40
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=9.4.0
- pint=0.20.1
- pip=22.3.1
- pixman=0.40.0
- pkgutil-resolve-name=1.3.10
- platformdirs=2.6.2
- ply=3.11
- pooch=1.6.0
- poppler=22.12.0
- poppler-data=0.4.11
- postgresql=15.1
- proj=9.1.0
- prometheus_client=0.15.0
- prompt-toolkit=3.0.36
- psutil=5.9.4
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pulseaudio=16.1
- pure_eval=0.2.2
- pycparser=2.21
- pygments=2.14.0
- pyopenssl=23.0.0
- pyparsing=3.0.9
- pyproj=3.4.1
- pyqt=5.15.7
- pyqt5-sip=12.11.0
- pyrsistent=0.19.3
- pyshp=2.3.1
- pysocks=1.7.1
- python=3.10.8
- python-dateutil=2.8.2
- python-fastjsonschema=2.16.2
- python-json-logger=2.0.4
- python_abi=3.10
- pytz=2022.7
- pyyaml=6.0
- pyzmq=25.0.0
- qt-main=5.15.6
- rasterio=1.3.4
- readline=8.1.2
- regionmask=0.9.0
- requests=2.28.1
- rfc3339-validator=0.1.4
- rfc3986-validator=0.1.1
- rioxarray=0.13.3
- rtree=1.0.1
- scikit-learn=1.2.0
- scipy=1.8.1
- send2trash=1.8.0
- setuptools=58.5.3
- shapely=1.8.5
- simpervisor=0.4
- sip=6.7.5
- six=1.16.0
- snappy=1.1.9
- sniffio=1.3.0
- snuggs=1.4.7
- sortedcontainers=2.4.0
- soupsieve=2.3.2.post1
- sparse=0.13.0
- sqlite=3.40.0
- stack_data=0.6.2
- statsmodels=0.13.5
- tblib=1.7.0
- terminado=0.17.1
- threadpoolctl=3.1.0
- tiledb=2.13.2
- tinycss2=1.2.1
- tk=8.6.12
- toml=0.10.2
- tomli=2.0.1
- toolz=0.12.0
- tornado=6.2
- traitlets=5.8.1
- typing-extensions=4.4.0
- typing_extensions=4.4.0
- tzcode=2022g
- tzdata=2022g
- unicodedata2=15.0.0
- urllib3=1.26.14
- wcwidth=0.2.5
- webencodings=0.5.1
- websocket-client=1.4.2
- wheel=0.38.4
- xarray=2022.12.0
- xcb-util=0.4.0
- xcb-util-image=0.4.0
- xcb-util-keysyms=0.4.0
- xcb-util-renderutil=0.3.9
- xcb-util-wm=0.4.1
- xclim=0.39.0
- xerces-c=3.2.4
- xesmf=0.7.0
- xorg-kbproto=1.0.7
- xorg-libice=1.0.10
- xorg-libsm=1.2.3
- xorg-libx11=1.7.2
- xorg-libxau=1.0.9
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.10
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xyzservices=2022.9.0
- xz=5.2.6
- yaml=0.2.5
- yarl=1.8.2
- zarr=2.13.3
- zeromq=4.3.4
- zict=2.2.0
- zipp=3.11.0
- zlib=1.2.13
- zstd=1.5.2

